# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: A Study Of Health Analytics Teams
email: buierw@uw.edu
description: >- # this means to ignore newlines until "baseurl:"
  A study of the work and organizational characteristics of analytics and data science teams across the health services
baseurl: "/health_analytics_teams" # the subpath of your site, e.g. /blog
basewebsite: /health_analytics_teams
url: "https://rwbuie.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# social links
twitter_username: 
github_username:  rwbuie
linkedin_username: rwbuie

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# minima specific options
#header_pages:
#  - summary.md
#  - privacy_risks.md
#  - prescreen.md
#  - about.md


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
